"use strict"

/**
 * SQLite schema — Screenshot Intelligence Layer
 *
 * Additive to Phase 1 (schema.js) and Intelligence Layer (intelligenceSchema.js).
 * Never modifies existing tables. Apply via applyScreenshotSchema(db).
 *
 * Purpose:
 *   Foundation for bettor psychology + screenshot intelligence.
 *   Stores ingested slips (from any source), structured leg parsing,
 *   classification scores, bettor archetype profiles, and outcome linkage.
 *
 * Design philosophy:
 *   - JSON files remain canonical for runtime
 *   - This layer is analytics + longitudinal learning only
 *   - Every table carries raw_json for schema-agnostic forward evolution
 *   - All ingestion sources treated uniformly — source_type distinguishes origin
 *   - No ML model weights stored here — only input features + classifications
 *
 * Table map:
 *   screenshot_submissions  — raw ingest records (one per submitted slip/screenshot)
 *   parsed_slips            — structured leg extraction from a submission
 *   slip_classifications    — scored dimensions for each parsed slip
 *   bettor_profiles         — longitudinal bettor archetype + preference model
 *   outcome_links           — connects an ingested slip to actual game results
 *
 * Source types (source_type column):
 *   'internal'    — AI-generated slip from this system (buildSlipAi.js)
 *   'personal'    — user's own placed bet from personal_ledger
 *   'screenshot'  — image upload parsed by AI (future phase)
 *   'twitter'     — slip pasted from Twitter/X
 *   'discord'     — slip pasted from Discord/betting community
 *   'viral'       — publicly viral parlay (from any source)
 *   'guru'        — slip attributed to a tipster/capper account
 *   'sportsbook'  — sportsbook promotional slip
 */

const DDL = `

-- ─────────────────────────────────────────────────────────────────────────────
-- screenshot_submissions
--
-- One row per submitted slip or screenshot ingestion event.
-- The raw intake record — before parsing, classification, or grading.
--
-- image_path: NULL for JSON ingestions; populated when actual image file
--   is stored (future phase — kept as nullable placeholder now).
-- raw_text: pasted text or OCR output from image (if available)
-- raw_json: full submitted payload as JSON (forward compat + re-parsing)
--
-- status lifecycle: pending → parsed → classified → graded → archived
--
-- ID: generated by caller as a stable hash or UUID. INSERT OR IGNORE
--   so re-submitting the same slip (e.g. re-analyzing) is idempotent
--   at the submission layer.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS screenshot_submissions (
  id              TEXT    PRIMARY KEY,
  submitted_at    TEXT    NOT NULL DEFAULT (datetime('now')),
  source_type     TEXT    NOT NULL,          -- internal / personal / screenshot / twitter / discord / viral / guru / sportsbook
  source_label    TEXT,                      -- e.g. "@SomeGuru", "DraftKings promo", "my parlay 5/8"
  sport           TEXT,                      -- mlb / nba / nfl / null if multi-sport
  slate_date      TEXT,                      -- YYYY-MM-DD or null if unknown
  image_path      TEXT,                      -- relative path to stored image file (null until image phase)
  raw_text        TEXT,                      -- pasted text or OCR output
  raw_json        TEXT,                      -- full submitted JSON payload
  status          TEXT    NOT NULL DEFAULT 'pending',   -- pending / parsed / classified / graded / archived
  notes           TEXT,
  created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ss_submitted  ON screenshot_submissions (submitted_at);
CREATE INDEX IF NOT EXISTS idx_ss_source     ON screenshot_submissions (source_type);
CREATE INDEX IF NOT EXISTS idx_ss_sport      ON screenshot_submissions (sport);
CREATE INDEX IF NOT EXISTS idx_ss_date       ON screenshot_submissions (slate_date);
CREATE INDEX IF NOT EXISTS idx_ss_status     ON screenshot_submissions (status);


-- ─────────────────────────────────────────────────────────────────────────────
-- parsed_slips
--
-- One row per structured slip extracted from a submission.
-- A single submission may yield multiple parsed slips (e.g. an image
-- containing three separate parlays).
--
-- Represents the normalized canonical form of any slip regardless of source.
-- All legs stored in legs_json — structured array for analysis.
--
-- legs_json shape (array of objects):
--   [
--     {
--       "player":     "Shohei Ohtani",       // null if team/game prop
--       "team":       "LAD",                  // optional
--       "statFamily": "hits",                 // normalized stat family
--       "propRaw":    "1+ Hits",              // original prop text if available
--       "side":       "over",                 // over / under / yes / no
--       "line":       0.5,                    // numeric line
--       "odds":       -145,                   // American odds (null if unknown)
--       "sportsbook": "DraftKings",           // null if not visible
--       "game":       "LAD vs NYM",           // raw game text if available
--       "eventId":    null                    // linked if matchable to our DB
--     }
--   ]
--
-- combined_odds: American odds for the full parlay (null if single leg)
-- total_legs: leg count for quick filtering without parsing legs_json
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS parsed_slips (
  id                  TEXT    PRIMARY KEY,
  submission_id       TEXT    NOT NULL REFERENCES screenshot_submissions(id),
  sport               TEXT,                      -- mlb / nba / nfl / mixed
  slate_date          TEXT,                      -- YYYY-MM-DD
  source_type         TEXT    NOT NULL,          -- inherited from submission
  total_legs          INTEGER NOT NULL DEFAULT 1,
  legs_json           TEXT    NOT NULL,          -- JSON array of leg objects (see above)
  combined_odds       INTEGER,                   -- American combined odds (null if single)
  combined_dec        REAL,                      -- decimal combined odds
  potential_payout    REAL,                      -- posted payout amount (null if not shown)
  stake               REAL,                      -- posted stake (null if not shown)
  currency            TEXT    DEFAULT 'USD',
  sportsbook          TEXT,                      -- primary sportsbook if determinable
  attribution         TEXT,                      -- who posted this (guru name, twitter handle, etc.)
  linked_internal_id  TEXT,                      -- ID of matching internal slip if auto-matched
  status              TEXT    NOT NULL DEFAULT 'pending',  -- pending / classified / graded
  raw_json            TEXT,
  created_at          TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ps2_submission  ON parsed_slips (submission_id);
CREATE INDEX IF NOT EXISTS idx_ps2_source      ON parsed_slips (source_type);
CREATE INDEX IF NOT EXISTS idx_ps2_sport       ON parsed_slips (sport);
CREATE INDEX IF NOT EXISTS idx_ps2_date        ON parsed_slips (slate_date);
CREATE INDEX IF NOT EXISTS idx_ps2_legs        ON parsed_slips (total_legs);
CREATE INDEX IF NOT EXISTS idx_ps2_sportsbook  ON parsed_slips (sportsbook);


-- ─────────────────────────────────────────────────────────────────────────────
-- slip_classifications
--
-- One row per classified slip. Linked to parsed_slips via slip_id.
-- Captures 10 scored dimensions (0.0 – 1.0 normalized) plus
-- composite signals and archetype tags.
--
-- Dimension definitions:
--   realism_score         — does the payout/odds structure make real-world sense?
--                           Low: $10→$50,000 on a 3-legger shown as "easy". High: honest EV.
--   structural_quality    — are legs well-diversified, appropriate leg count, sensible combo?
--                           Low: 6-leg all-same-stat. High: 3-leg cross-sport diversified.
--   correlation_quality   — are legs from independent outcomes vs script-correlated?
--                           Low: 4 overs from same game. High: 3 legs from 3 games.
--   hidden_sharpness      — does the structure contain genuine edge signals?
--                           Low: all chalk unders near -200. High: +EV alt-lines.
--   emotional_bait        — does the slip use psychological manipulation?
--                           High: huge payout headline, "easy money", streak shown. Low: neutral.
--   volatility_structure  — is the volatility mix coherent or incoherent?
--                           High: randomly mixed safe+lotto legs with no narrative. Low: clean tier.
--   payout_realism        — is the stated payout mathematically honest?
--                           Low: overstated payout for the odds shown. High: matches math.
--   exploit_potential     — does the structure exploit known book weaknesses?
--                           High: same-game parlay on correlated outcomes vs a soft book.
--   appeal_score          — how emotionally seductive is this slip to Andy specifically?
--                           (learned from preference_signals over time)
--   ecology_fit           — how well does this slip's stat/side/tier mix match system ecology?
--                           High: matches what our model would build. Low: random/guru.
--
-- archetype: PRIMARY bettor/slip archetype (see ARCHETYPE reference below)
-- archetype_tags: JSON array of secondary tags
-- ecology_tags: JSON array of ecology classification tags
--
-- ARCHETYPE reference:
--   'sharp_aggressive'   — genuine edge + high-volatility + non-obvious construction
--   'recreational_chase' — low-edge high-payout chasing, emotionally driven
--   'guru_bait'          — tipster-style, looks impressive, structurally weak
--   'viral_lotto'        — extreme longshot engineered for shareability
--   'safe_grind'         — low-volatility, process-driven, appropriate sizing
--   'sportsbook_trap'    — promoted by book, typically low-EV
--   'unknown'            — insufficient signals to classify
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS slip_classifications (
  id                    TEXT    PRIMARY KEY,
  slip_id               TEXT    NOT NULL REFERENCES parsed_slips(id),
  classified_at         TEXT    NOT NULL DEFAULT (datetime('now')),
  classifier_version    TEXT    NOT NULL DEFAULT 'v1',

  -- 10 scored dimensions (0.0 = worst, 1.0 = best on each scale)
  realism_score         REAL,    -- payout/odds honesty (1.0 = fully honest)
  structural_quality    REAL,    -- leg diversity and construction quality
  correlation_quality   REAL,    -- outcome independence (1.0 = fully independent)
  hidden_sharpness      REAL,    -- embedded genuine edge signals
  emotional_bait        REAL,    -- psychological manipulation (1.0 = HIGH manipulation — inverted intentionally)
  volatility_structure  REAL,    -- coherence of volatility tier mix (1.0 = coherent)
  payout_realism        REAL,    -- mathematical accuracy of stated payout
  exploit_potential     REAL,    -- exploiting known book weaknesses
  appeal_score          REAL,    -- personal appeal to Andy (learned; starts null)
  ecology_fit           REAL,    -- alignment with system's candidate ecology

  -- composite signals
  composite_score       REAL,    -- weighted aggregate across all dimensions
  sharp_signal          INTEGER, -- 1 if hidden_sharpness >= 0.65 AND emotional_bait <= 0.35
  bait_signal           INTEGER, -- 1 if emotional_bait >= 0.65 AND hidden_sharpness <= 0.40
  viral_signal          INTEGER, -- 1 if payout_realism <= 0.30 (inflated payout structure)

  -- archetype classification
  archetype             TEXT    NOT NULL DEFAULT 'unknown',
  archetype_tags        TEXT,    -- JSON array of secondary tags
  ecology_tags          TEXT,    -- JSON array: ['offensive_heavy', 'under_biased', 'lotto_structure', ...]

  -- scoring rationale (compact human-readable)
  rationale             TEXT,    -- brief explanation of top classification signals

  raw_json              TEXT,
  created_at            TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_sc2_slip        ON slip_classifications (slip_id);
CREATE INDEX IF NOT EXISTS idx_sc2_archetype   ON slip_classifications (archetype);
CREATE INDEX IF NOT EXISTS idx_sc2_composite   ON slip_classifications (composite_score);
CREATE INDEX IF NOT EXISTS idx_sc2_sharp       ON slip_classifications (sharp_signal);
CREATE INDEX IF NOT EXISTS idx_sc2_bait        ON slip_classifications (bait_signal);
CREATE INDEX IF NOT EXISTS idx_sc2_viral       ON slip_classifications (viral_signal);


-- ─────────────────────────────────────────────────────────────────────────────
-- bettor_profiles
--
-- One row per tracked bettor/source entity.
-- Longitudinal model of a bettor's patterns, preferences, and performance.
--
-- Built incrementally: each new ingested slip from this source updates the profile.
-- Andy's own profile (source_type='personal') is the primary target — it learns
-- what he actually bets, what hits, and what emotionally appeals to him.
--
-- preference_signals: JSON object capturing rolling signals about what this
--   bettor gravitates toward (stat families, volatility, side bias, leg count, etc.)
--   Shape:
--   {
--     "statFamilies":   { "hits": 0.32, "totalBases": 0.28, ... },  // fraction of legs
--     "sideBias":       { "over": 0.45, "under": 0.55 },
--     "volatilityMix":  { "safe": 0.20, "balanced": 0.45, "aggressive": 0.30, "lotto": 0.05 },
--     "avgLegCount":    2.8,
--     "avgOdds":        185,
--     "sportsbooks":    { "DraftKings": 0.55, "FanDuel": 0.30, ... },
--     "avgEdge":        0.087,
--     "avgEV":          0.12
--   }
--
-- outcome_stats: rolling hit rate + ROI by archetype/tier
-- slip_count: total slips ingested from this source
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bettor_profiles (
  id                TEXT    PRIMARY KEY,    -- 'andy' for personal, or normalized source key
  display_name      TEXT    NOT NULL,       -- human-readable name
  source_type       TEXT    NOT NULL,       -- personal / guru / viral / discord
  sport_focus       TEXT,                   -- primary sport or 'multi'
  slip_count        INTEGER DEFAULT 0,
  classified_count  INTEGER DEFAULT 0,
  graded_count      INTEGER DEFAULT 0,

  -- archetype distribution (JSON: how often each archetype appears)
  archetype_dist    TEXT,   -- JSON: { "sharp_aggressive": 0.12, "safe_grind": 0.55, ... }

  -- preference signals (JSON — see above)
  preference_signals TEXT,

  -- outcome tracking (JSON)
  -- { "hitRate": 0.54, "roi": 0.08, "byArchetype": { "safe_grind": { "hitRate": 0.62, "roi": 0.12 } } }
  outcome_stats     TEXT,

  -- ecology alignment (JSON — how well does this bettor's pool match our model?)
  ecology_alignment TEXT,  -- { "overallFit": 0.72, "byStatFamily": { "hits": 0.81, ... } }

  first_seen        TEXT    NOT NULL DEFAULT (datetime('now')),
  last_updated      TEXT    NOT NULL DEFAULT (datetime('now')),
  notes             TEXT,
  raw_json          TEXT,
  created_at        TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_bp_source       ON bettor_profiles (source_type);
CREATE INDEX IF NOT EXISTS idx_bp_last_updated ON bettor_profiles (last_updated);


-- ─────────────────────────────────────────────────────────────────────────────
-- outcome_links
--
-- One row per graded leg from an ingested slip.
-- Links a parsed_slip leg to actual game results.
--
-- This is how the system learns over time:
--   - Guru slips that look sharp but consistently miss → low hidden_sharpness
--   - Andy's preferred slip structures that hit → high appeal_score reinforcement
--   - Viral parlays that are structurally terrible → confirm bait_signal model
--
-- Can be populated:
--   a) Manually by operator after game completion
--   b) Automatically via buildPostGameReview.js integration (future phase)
--   c) Via outcome_snapshots join on (player, stat_family, side, line, date)
--
-- actual_value: the stat that actually occurred
-- hit: 1 = leg won, 0 = leg lost, NULL = void/push/unknown
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS outcome_links (
  id              TEXT    PRIMARY KEY,
  slip_id         TEXT    NOT NULL REFERENCES parsed_slips(id),
  leg_index       INTEGER NOT NULL,         -- 0-based index into legs_json array
  player          TEXT,
  stat_family     TEXT,
  side            TEXT,
  line            REAL,
  slate_date      TEXT,
  actual_value    REAL,                     -- actual stat (e.g. 2 hits, 1 HR)
  hit             INTEGER,                  -- 1 = won, 0 = lost, NULL = pending/void
  slip_won        INTEGER,                  -- 1 = full parlay won, 0 = lost, NULL = pending
  source          TEXT    DEFAULT 'manual', -- manual / postGameReview / outcomeSnapshot
  settled_at      TEXT,
  notes           TEXT,
  raw_json        TEXT,
  created_at      TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_ol_slip         ON outcome_links (slip_id);
CREATE INDEX IF NOT EXISTS idx_ol_date         ON outcome_links (slate_date);
CREATE INDEX IF NOT EXISTS idx_ol_player       ON outcome_links (player);
CREATE INDEX IF NOT EXISTS idx_ol_hit          ON outcome_links (hit);
CREATE INDEX IF NOT EXISTS idx_ol_slip_won     ON outcome_links (slip_won);

`

/**
 * Apply the screenshot intelligence schema to an open DatabaseSync instance.
 * Safe to call multiple times — all statements use CREATE IF NOT EXISTS.
 *
 * @param {import('node:sqlite').DatabaseSync} db
 */
function applyScreenshotSchema(db) {
  db.exec(DDL)
}

module.exports = { applyScreenshotSchema, DDL }
